# Generated by Django 5.1.2 on 2025-03-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='web.products'),
        ),
    ]
