# Generated by Django 5.1.2 on 2025-03-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_products_category_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cart_value',
        ),
    ]
