# Generated by Django 5.1.2 on 2025-03-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="web/static/assets/images/demos/demo-13/products/",
            ),
        ),
    ]
